# Generated by Django 4.2.6 on 2023-10-18 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NameCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_con', models.CharField(choices=[('p', 'Plug Housing'), ('s', 'Socked Housing')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PinNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RowNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_con', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Using',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('using', models.CharField(choices=[('w', 'Wire Harness'), ('p', 'PCB')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=10)),
                ('customer_number', models.CharField(max_length=15)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectordb.manufacturer')),
                ('name_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectordb.namecon')),
                ('pin_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectordb.pinnumber')),
                ('row_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectordb.rownumber')),
                ('type_con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectordb.typecon')),
                ('using', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectordb.using')),
            ],
        ),
    ]
