# Generated by Django 4.2.6 on 2023-10-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectordb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namecon',
            name='name_con',
            field=models.CharField(choices=[('Plug Housing', 'Plug Housing'), ('Socked Housing', 'Socked Housing')], max_length=50),
        ),
    ]
