# Generated by Django 4.2.6 on 2023-10-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectordb', '0002_alter_namecon_name_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='id',
        ),
        migrations.AlterField(
            model_name='connector',
            name='part_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='using',
            name='using',
            field=models.CharField(choices=[('Wire Harness', 'Wire Harness'), ('PCB', 'PCB')], max_length=20),
        ),
    ]
