# Generated by Django 4.2.6 on 2023-10-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectordb', '0003_remove_connector_id_alter_connector_part_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_name', models.CharField(max_length=50)),
            ]
        ),

        migrations.AddField(
            model_name='connector',
            name='connector_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='connectordb.connectorname'),
            preserve_default=False,
        )
        ]

