# Generated by Django 4.2.6 on 2023-10-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectordb', '0004_connectorname_remove_connector_name_con_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connector',
            name='name_con',
        ),
        migrations.DeleteModel(
            name='NameCon',
        ),
    ]
