# Generated by Django 4.2.6 on 2023-10-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectordb', '0005_remove_connector_name_con_delete_namecon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectorname',
            name='connector_name',
            field=models.CharField(choices=[('Plug Housing', 'Plug Housing'), ('Socked Housing', 'Socked Housing')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rownumber',
            name='row_number',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')]),
        ),
    ]
